// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma-next contract emit'.
// To regenerate, run: prisma-next contract emit
import type { CodecTypes as PgTypes } from '@prisma-next/target-postgres/codec-types';
import type { JsonValue } from '@prisma-next/target-postgres/codec-types';
import type { Char } from '@prisma-next/target-postgres/codec-types';
import type { Varchar } from '@prisma-next/target-postgres/codec-types';
import type { Numeric } from '@prisma-next/target-postgres/codec-types';
import type { Bit } from '@prisma-next/target-postgres/codec-types';
import type { VarBit } from '@prisma-next/target-postgres/codec-types';
import type { Timestamp } from '@prisma-next/target-postgres/codec-types';
import type { Timestamptz } from '@prisma-next/target-postgres/codec-types';
import type { Time } from '@prisma-next/target-postgres/codec-types';
import type { Timetz } from '@prisma-next/target-postgres/codec-types';
import type { Interval } from '@prisma-next/target-postgres/codec-types';
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma-next/adapter-postgres/operation-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma-next/sql-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma-next/contract/types';

export type StorageHash =
  StorageHashBase<'sha256:1e56be8e129d88ab934a43c00965862bbf7225adc09a58dd46ac656fdb54705b'>;
export type ExecutionHash =
  ExecutionHashBase<'sha256:75777f07d9168fa8a218e1e8fc54a57ebcae7e2826eb6c3503749c361bccf0b5'>;
export type ProfileHash =
  ProfileHashBase<'sha256:1a8dbe044289f30a1de958fe800cc5a8378b285d2e126a8c44b58864bac2c18e'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
type DefaultLiteralValue<CodecId extends string, _Encoded> = CodecId extends keyof CodecTypes
  ? CodecTypes[CodecId]['output']
  : _Encoded;

export type FieldOutputTypes = {
  readonly Poi: {
    readonly id: CodecTypes['pg/int4@1']['output'];
    readonly name: CodecTypes['pg/text@1']['output'];
    readonly latitude: CodecTypes['pg/float8@1']['output'];
    readonly longitude: CodecTypes['pg/float8@1']['output'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['output'];
    readonly updatedAt: CodecTypes['pg/timestamptz@1']['output'];
  };
};
export type FieldInputTypes = {
  readonly Poi: {
    readonly id: CodecTypes['pg/int4@1']['input'];
    readonly name: CodecTypes['pg/text@1']['input'];
    readonly latitude: CodecTypes['pg/float8@1']['input'];
    readonly longitude: CodecTypes['pg/float8@1']['input'];
    readonly createdAt: CodecTypes['pg/timestamptz@1']['input'];
    readonly updatedAt: CodecTypes['pg/timestamptz@1']['input'];
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes
>;

type ContractBase = ContractType<
  {
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'sql-namespace';
        readonly tables: {
          readonly poi: {
            columns: {
              readonly id: {
                readonly nativeType: 'int4';
                readonly codecId: 'pg/int4@1';
                readonly nullable: false;
                readonly default: {
                  readonly kind: 'function';
                  readonly expression: 'autoincrement()';
                };
              };
              readonly name: {
                readonly nativeType: 'text';
                readonly codecId: 'pg/text@1';
                readonly nullable: false;
              };
              readonly latitude: {
                readonly nativeType: 'float8';
                readonly codecId: 'pg/float8@1';
                readonly nullable: false;
              };
              readonly longitude: {
                readonly nativeType: 'float8';
                readonly codecId: 'pg/float8@1';
                readonly nullable: false;
              };
              readonly createdAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
                readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
              };
              readonly updatedAt: {
                readonly nativeType: 'timestamptz';
                readonly codecId: 'pg/timestamptz@1';
                readonly nullable: false;
              };
            };
            primaryKey: { readonly columns: readonly ['id'] };
            uniques: readonly [];
            indexes: readonly [];
            foreignKeys: readonly [];
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  },
  {
    readonly Poi: {
      readonly fields: {
        readonly id: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
        };
        readonly name: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
        };
        readonly latitude: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
        };
        readonly longitude: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
        };
        readonly createdAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
        readonly updatedAt: {
          readonly nullable: false;
          readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/timestamptz@1' };
        };
      };
      readonly relations: Record<string, never>;
      readonly storage: {
        readonly table: 'poi';
        readonly fields: {
          readonly id: { readonly column: 'id' };
          readonly name: { readonly column: 'name' };
          readonly latitude: { readonly column: 'latitude' };
          readonly longitude: { readonly column: 'longitude' };
          readonly createdAt: { readonly column: 'createdAt' };
          readonly updatedAt: { readonly column: 'updatedAt' };
        };
      };
    };
  }
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: { readonly poi: 'Poi' };
  readonly capabilities: {
    readonly postgres: {
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly returning: true;
    };
  };
  readonly extensionPacks: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: { readonly table: 'poi'; readonly column: 'updatedAt' };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
export type Models = Contract['models'];
